const allMessages = 
{
    en : {
        EMAIL_EXIST: "Email already exists",
        FAIL_GENERATE_TOKEN: "Failed To Generate Token",
        SUCCESS_CREATE_USER: "user created successfully and email sent successfully" ,
        SUCCESS: "success" ,
        INVALID_INFO: "in-valid informations",
        FAIL_LOGIN: "Login Failed",
        FAIL: "Somthig went wrong" ,
        USER_NOT_EXIST: "user does not exist",
        USER_EXIST: "user already exist",
        SUCCESS_LOGGED_IN: "user logged in successfully",
        EMAIL_ALREADY_CONFIRMED: "Email is Already Confirmed",
        FAIL_CONFIRM_EMAIL: "Confiramtion is Failed", 
        SUCCESS_CONFIRM_EMAIL:"Email confirmed successfully" ,
        SUCCESS_DELETE_USER:"user deleted successfully" ,
        FAIL_DELETE_USER:"failed to delete user" ,
        SUCCESS_UPDATE_USER:"user updated successfully" ,
        FAIL_UPDATE_USER:"failed to update user" ,
        NOTE_DELETE_USER:"user will delete permenantly after 12:00 am" ,
        FAIL_SEND_EMAIL:"failed to send email" ,
        FAIL_PASS_MATCHING:"passwords mismatch" ,
        FAIL_UPLOAD_PIC:"upload image failed" ,
        FAIL_ADD_POST:"failed to add post",
        SUCCESS_ADD_POST:"post added successfully",
        FAIL_UPDATE_POST:"failed to update post",
        SUCCESS_DELETE_POST:"post deleted successfully",
        FAIL_DELETE_POST:"failed to delete post",
        SUCCESS_BUY_POST:"your order proceeded successfully",
        FAIL_BUY_POST:"failed to proceed your order ",
        FAIL_SEARCH_POST:"No posts found",
        ALREADY_LIKED:"user already liked this post",
        ALREADY_NOT_LIKED:"user already not liked this post",
        SUCCESS_ADD_COMMENT:"successfully added comment",
        NOT_FOUND:"not found by this id",
        NOT_AUTHORIZED:"user not authorized to take action",
        NAME_EXIST:"user name already exists",

        } ,
    ar:  {
        EMAIL_EXIST: "الايميل موجود بالفعل",
        FAIL_GENERATE_TOKEN: "فشل في إنشاء الرمز",
        SUCCESS_CREATE_USER: " تم إنشاء الحساب بنجاح وتم إرسال رمز التفعيل على الايميل" ,
        INVALID_INFO: "المعلومات غير صحيحه" ,
        FAIL_LOGIN: "حدث خطأ تعذر الدخول إلى الحساب" ,
        FAIL: "حدث خطأ " ,
        SUCCESS: "تمت العملية بنجاح" ,
        USER_NOT_EXIST: "المستخدم غير موجود" ,
        USER_EXIST: "المستخدم موجود من قبل",
        SUCCESS_LOGGED_IN: "تم تسجيل الدخول بنجاح" ,
        EMAIL_ALREADY_CONFIRMED: "الحساب مفعل من قبل" ,
        FAIL_CONFIRM_EMAIL: "حدث خطأ يتعذر تفعيل الحساب " ,
        SUCCESS_CONFIRM_EMAIL: "تم تفعيل الحساب" ,
        SUCCESS_DELETE_USER:"تم حذف الحساب بنجاح" ,
        FAIL_DELETE_USER:"حدث خطأ أثناء حذف الحساب" ,
        SUCCESS_UPDATE_USER:"تم تحديث بيانات الحساب بنجاح" ,
        FAIL_UPDATE_USER:"حدث خطأ أثناء تحديث بيانات الحساب" ,
        NOTE_DELETE_USER:"تنبيه سيتم حذف البيانات نهائياً الساعه 12:00 صباحاً" ,
        FAIL_SEND_EMAIL:"حدث خطأ أثناء إرسال الايميل" ,
        FAIL_PASS_MATCHING:"الرمز القديم غي صحيح" ,
        FAIL_UPLOAD_PIC:"حدث خطأ أثناء رفع الصوره" ,
        SUCCESS_ADD_POST:"تم اضافة المنتج بنجاح",
        FAIL_ADD_POST:"حدث خطأ اثناء اضافة المنتج",
        SUCCESS_UPDATE_POST:"تم تحديث معلومات المنتج بنجاح",
        FAIL_UPDATE_POST:"حدث خطأ اثناء تحديث معلومات المنتج ",
        SUCCESS_DELETE_POST:"تم مسح المنتج بنجاح ",
        FAIL_DELETE_POST:"حدث خطأ اثناء مسح المنتج",
        SUCCESS_BUY_POST:"تم شراء طلبك بنجاح ",
        FAIL_BUY_POST:"حدث خطأاثناء الشراء ",
        FAIL_SEARCH_POST:"لم يتم العثور علي المنتج ",
        ALREADY_LIKED:"المستخدم معجب بالمنشور من قبل",
        ALREADY_NOT_LIKED:"المستخدم لم يعجبه المنشور من قبل",
        SUCCESS_ADD_COMMENT:"تمت إضافة تعليق بنجاح",
        NOT_FOUND:"ما تبحث عنه غير موجود",
        NOT_AUTHORIZED:"غير مصرح للمستخدم بإتخاز القرار",
        NAME_EXIST:"الإسم مستخدم من قبل",
    }
  
}


export function translateResponse (message){  
    return allMessages[process.env.lang][message]
}

export const allResponsesMessages = 
{
        EMAIL_EXIST:"EMAIL_EXIST",
        NAME_EXIST:"NAME_EXIST",
        FAIL_GENERATE_TOKEN:"FAIL_GENERATE_TOKEN",
        SUCCESS_CREATE_USER:"SUCCESS_CREATE_USER" ,
        INVALID_INFO:"INVALID_INFO" ,
        FAIL_LOGIN:"FAIL_LOGIN" ,
        FAIL:"FAIL" ,
        USER_NOT_EXIST:"USER_NOT_EXIST" ,
        USER_EXIST:"USER_EXIST" ,
        SUCCESS_LOGGED_IN:"SUCCESS_LOGGED_IN" ,
        EMAIL_ALREADY_CONFIRMED:"EMAIL_ALREADY_CONFIRMED" ,
        FAIL_CONFIRM_EMAIL:"FAIL_CONFIRM_EMAIL" ,
        SUCCESS_CONFIRM_EMAIL:"SUCCESS_CONFIRM_EMAIL" ,
        SUCCESS_DELETE_USER:"SUCCESS_DELETE_USER" ,
        FAIL_DELETE_USER:"FAIL_DELETE_USER" ,
        SUCCESS_UPDATE_USER:"SUCCESS_UPDATE_USER" ,
        FAIL_UPDATE_USER:"FAIL_UPDATE_USER" ,
        NOTE_DELETE_USER:"NOTE_DELETE_USER" ,
        FAIL_SEND_EMAIL:"FAIL_SEND_EMAIL" ,
        SUCCESS:"SUCCESS" ,
        FAIL_PASS_MATCHING:"FAIL_PASS_MATCHING" ,
        FAIL_UPLOAD_PIC:"FAIL_UPLOAD_PIC" ,
        ALREADY_LIKED:"ALREADY_LIKED" ,
        ALREADY_NOT_LIKED:"ALREADY_NOT_LIKED" ,
        SUCCESS_ADD_COMMENT:"SUCCESS_ADD_COMMENT" ,
        SUCCESS_ADD_POST:"SUCCESS_ADD_POST",
        SUCCEES_ADD_COMMENT:"SUCCESS_ADD_COMMENT",
        FAIL_ADD_POST:"FAIL_ADD_POST",
        FAIL_ADD_COMMENT:"FAIL_ADD_COMMENT",
        SUCCESS_UPDATE_POST:" SUCCESS_UPDATE_POST",
        FAIL_UPDATE_POST:"FAIL_UPDATE_POST",
        SUCCESS_DELETE_POST:"SUCCES_DELETE_POST",
        FAIL_DELETE_POST:"FAIL_DELETE_POST",
        SUCCESS_BUY_POST:"SUCCESS_BUY_POST",
        FAIL_BUY_POST:"FAIL_BUY_POST",
        FAIL_SEARCH_POST:"FAIL_SEARCH_POST",
        NOT_FOUND:"NOT_FOUND",
        NOT_AUTHORIZED:"NOT_AUTHORIZED",
        NOT_AUTHORIZED:"NOT_AUTHORIZED",
  
}